-- Create Trade Risk Analytics Table
CREATE TABLE TRADE_RISK_ANALYTICS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    COUNTRY NVARCHAR(100) NOT NULL,
    PRODUCT_CATEGORY NVARCHAR(100) NOT NULL,
    POLITICAL_RISK_SCORE DECIMAL(3,1) NOT NULL,
    ECONOMIC_RISK_SCORE DECIMAL(3,1) NOT NULL,
    CURRENCY_RISK_SCORE DECIMAL(3,1) NOT NULL,
    OVERALL_RISK_SCORE DECIMAL(3,1) NOT NULL,
    RISK_FACTORS NCLOB,
    MITIGATION_STRATEGIES NCLOB,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample trade risk data
INSERT INTO TRADE_RISK_ANALYTICS (COUNTRY, PRODUCT_CATEGORY, POLITICAL_RISK_SCORE, ECONOMIC_RISK_SCORE, CURRENCY_RISK_SCORE, OVERALL_RISK_SCORE, RISK_FACTORS, MITIGATION_STRATEGIES) VALUES
('United States', 'Electronics', 2.1, 2.8, 3.2, 2.7, 'Trade policy changes, regulatory compliance requirements', 'Diversify suppliers, maintain compliance documentation, monitor policy changes'),
('United States', 'Textiles', 2.3, 2.5, 3.2, 2.7, 'Import quotas, anti-dumping duties', 'Establish local partnerships, consider nearshoring options'),
('United States', 'Automotive', 2.0, 2.9, 3.2, 2.7, 'Safety regulations, environmental standards', 'Invest in R&D for compliance, build local manufacturing'),

('Germany', 'Electronics', 1.8, 2.2, 2.8, 2.3, 'EU regulations, environmental compliance', 'Obtain CE marking, establish EU distribution network'),
('Germany', 'Textiles', 1.9, 2.1, 2.8, 2.3, 'Labor standards, sustainability requirements', 'Implement sustainable practices, obtain certifications'),
('Germany', 'Automotive', 1.7, 2.0, 2.8, 2.2, 'Emission standards, safety regulations', 'Invest in green technology, partner with local suppliers'),

('China', 'Electronics', 3.2, 3.5, 4.1, 3.6, 'Regulatory changes, IP protection concerns', 'Secure IP rights, maintain government relations'),
('China', 'Textiles', 3.0, 3.3, 4.1, 3.5, 'Labor cost increases, environmental regulations', 'Automate production, implement green practices'),
('China', 'Automotive', 3.1, 3.4, 4.1, 3.5, 'Local content requirements, joint venture mandates', 'Form strategic partnerships, localize supply chain'),

('Brazil', 'Electronics', 4.2, 4.8, 5.2, 4.7, 'High import duties, complex regulations', 'Consider local assembly, navigate bureaucracy carefully'),
('Brazil', 'Textiles', 4.0, 4.5, 5.2, 4.6, 'Currency volatility, import restrictions', 'Use hedging strategies, establish local presence'),
('Brazil', 'Automotive', 3.9, 4.3, 5.2, 4.5, 'Local content requirements, tax incentives', 'Invest in local production, leverage incentives'),

('Japan', 'Electronics', 1.5, 2.0, 2.5, 2.0, 'Quality standards, certification requirements', 'Meet JIS standards, build quality reputation'),
('Japan', 'Textiles', 1.6, 2.1, 2.5, 2.1, 'Consumer preferences, seasonal demand', 'Adapt to local tastes, manage inventory carefully'),
('Japan', 'Automotive', 1.4, 1.9, 2.5, 1.9, 'Safety standards, environmental regulations', 'Invest in safety technology, meet emission standards'),

('United Kingdom', 'Electronics', 2.5, 3.1, 3.8, 3.1, 'Post-Brexit regulations, currency volatility', 'Monitor regulatory changes, use currency hedging'),
('United Kingdom', 'Textiles', 2.6, 3.0, 3.8, 3.1, 'New trade agreements, supply chain disruptions', 'Diversify supply chains, leverage new trade deals'),
('United Kingdom', 'Automotive', 2.4, 2.9, 3.8, 3.0, 'Rules of origin, regulatory alignment', 'Ensure compliance with new rules, maintain EU standards');

-- Create indexes for better performance
CREATE INDEX IDX_TRADE_RISK_COUNTRY ON TRADE_RISK_ANALYTICS(COUNTRY);
CREATE INDEX IDX_TRADE_RISK_PRODUCT ON TRADE_RISK_ANALYTICS(PRODUCT_CATEGORY);
CREATE INDEX IDX_TRADE_RISK_UPDATED ON TRADE_RISK_ANALYTICS(LAST_UPDATED);
