-- Create Market Intelligence Table
CREATE TABLE MARKET_INTELLIGENCE (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REGION NVARCHAR(100) NOT NULL,
    PRODUCT_CATEGORY NVARCHAR(100) NOT NULL,
    MARKET_SIZE_USD BIGINT NOT NULL,
    GROWTH_RATE DECIMAL(4,2) NOT NULL,
    COMPETITION_LEVEL NVARCHAR(20) NOT NULL,
    KEY_OPPORTUNITIES NCLOB,
    MARKET_WARNINGS NCLOB,
    INVESTMENT_REQUIRED BIGINT,
    TIMEFRAME NVARCHAR(10) NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample market intelligence data
INSERT INTO MARKET_INTELLIGENCE (REGION, PRODUCT_CATEGORY, MARKET_SIZE_USD, GROWTH_RATE, COMPETITION_LEVEL, KEY_OPPORTUNITIES, MARKET_WARNINGS, INVESTMENT_REQUIRED, TIMEFRAME) VALUES
('North America', 'Electronics', 520000000000, 5.8, 'High', 'AI integration, 5G adoption, smart home devices', 'Supply chain disruptions, semiconductor shortages', 2500000, '12m'),
('North America', 'Textiles', 95000000000, 3.2, 'Medium', 'Sustainable fashion, e-commerce growth', 'Fast fashion competition, labor cost pressures', 800000, '12m'),
('North America', 'Automotive', 680000000000, 4.1, 'High', 'Electric vehicles, autonomous driving', 'Regulatory changes, battery supply constraints', 5000000, '12m'),

('Europe', 'Electronics', 380000000000, 4.5, 'High', 'Green technology, Industry 4.0', 'Regulatory compliance costs, energy prices', 2000000, '12m'),
('Europe', 'Textiles', 180000000000, 2.8, 'Medium', 'Circular economy, premium brands', 'Sustainability regulations, cost pressures', 1200000, '12m'),
('Europe', 'Automotive', 450000000000, 3.7, 'High', 'Electric mobility, connected cars', 'Emission regulations, market saturation', 4500000, '12m'),

('Asia Pacific', 'Electronics', 850000000000, 8.9, 'Very High', 'Mobile technology, IoT expansion', 'Trade tensions, component shortages', 1800000, '12m'),
('Asia Pacific', 'Textiles', 320000000000, 6.5, 'Very High', 'Fast fashion, online retail', 'Labor cost increases, environmental concerns', 600000, '12m'),
('Asia Pacific', 'Automotive', 720000000000, 7.2, 'Very High', 'Electric vehicles, shared mobility', 'Infrastructure challenges, regulatory variations', 3500000, '12m'),

('Latin America', 'Electronics', 85000000000, 6.8, 'Medium', 'Digital transformation, mobile adoption', 'Currency volatility, import restrictions', 1200000, '12m'),
('Latin America', 'Textiles', 45000000000, 4.2, 'Medium', 'Nearshoring opportunities, local brands', 'Economic instability, infrastructure gaps', 500000, '12m'),
('Latin America', 'Automotive', 120000000000, 5.5, 'Medium', 'Local assembly, government incentives', 'Economic volatility, financing challenges', 2800000, '12m'),

('Middle East & Africa', 'Electronics', 65000000000, 9.2, 'Medium', 'Digital infrastructure, smart cities', 'Political instability, import dependencies', 1500000, '12m'),
('Middle East & Africa', 'Textiles', 35000000000, 7.1, 'Low', 'Cotton production, export potential', 'Infrastructure limitations, skill gaps', 400000, '12m'),
('Middle East & Africa', 'Automotive', 55000000000, 8.3, 'Low', 'Assembly operations, government support', 'Import dependency, financing constraints', 2200000, '12m'),

('Global', 'Electronics', 1800000000000, 6.2, 'Very High', 'AI, IoT, 5G convergence', 'Supply chain complexity, geopolitical tensions', 15000000, '12m'),
('Global', 'Textiles', 675000000000, 4.1, 'High', 'Sustainability, digitalization', 'Environmental regulations, cost pressures', 5000000, '12m'),
('Global', 'Automotive', 2800000000000, 5.4, 'Very High', 'Electrification, autonomous driving', 'Regulatory changes, technology disruption', 25000000, '12m');

-- Create indexes for better performance
CREATE INDEX IDX_MARKET_INTEL_REGION ON MARKET_INTELLIGENCE(REGION);
CREATE INDEX IDX_MARKET_INTEL_PRODUCT ON MARKET_INTELLIGENCE(PRODUCT_CATEGORY);
CREATE INDEX IDX_MARKET_INTEL_TIMEFRAME ON MARKET_INTELLIGENCE(TIMEFRAME);
CREATE INDEX IDX_MARKET_INTEL_UPDATED ON MARKET_INTELLIGENCE(LAST_UPDATED);
